### ISSUE TITLE
Consider methods of payment other than Bitcoin

### ISSUE THREAD

**Issue by bhaugen** [joshuavial/sustain#13]
I think this project is a great idea and don't want to slow it down, so I will not complain if you tag this "for later".

But Simon's intro on Loomio said, 

> List our economic dependencies and contributions and contact them:“how do we give you money?”

Reasons for suggestion:
- Bitcoins will have some setup hurdles and costs for people who are not using them yet.
- They will also be distasteful to some people (like me). I can get over that for the sake of participating in this project, but you might want to hear that.
- Even in the digital currency realm, other alternatives with different properties are emerging. For example, http://bollier.org/blog/faircoin-first-global-commons-currency

To repeat, I am not suggesting you do anything about this issue now. But it was the first issue that came to my mind when I looked at the proposal, which I dearly love.

**Comment by joshuavial** [comment]
Absolutely agree, I'm not a huge fan bitcoin fan by any means and think we should integrate with any popular cryptocurrency. My main thinking was to go for the easy win that would give us decentralised payments with a currency that is reasonably well adopted so people can turn it into real money easily enough.

**Comment by bhaugen** [comment]
All fine with me.

**Comment by ahdinosaur** [comment]
btw, @mmckegg is [interested in using sustain](https://github.com/mmckegg/loop-drop-app/issues/94) to redistribute incoming revenue from Loop Drop sales using PayPal. i wonder if we could make the commands that involve the actual payment distribution part pluggable, so we could have a Bitcoin plugin or a Paypal plugin, etc.

**Comment by joshuavial** [comment]
Yep, I think making a plugin based system for different payment mechanisms would be a reasonable way to go.

**Comment by joshuavial** [comment]
https://github.com/joshuavial/sustain/issues/23 has the ticket for extracting the initial bitcoin code into a plugin.
